### PR TITLE
Updated README.md file

### PR DESCRIPTION
**Pull request by DustinoZhang**
Now includes information about trie implementation, how to use the redis module commands, information about installing Redis and Redis provided data types

### CODE REVIEW

**Comment by mpcsh** [comment]
@charles37 Please review this ASAP.

**Comment by mpcsh** [comment]
@DustinoZhang Looks like other people contributed commits here as well - should we add some assignees?

**Comment by DustinoZhang** [comment]
@mpcsh I'm not 100% on this but I think those go away when https://github.com/cmsc22000-project-2018/redis-tries/pull/45 this gets merged into the master. If not when the other PR gets merged, I'll add the appropriate assignees

**Comment by DustinoZhang** [comment]
I created this branch off the dev branch however and only edited the readme.MD file on it (as well as restoring the trie.c file so it wouldn't carry any other commits from other people's branches but that only helped to a certain extent)

**Pull request merged**
