### PR TITLE
add author name Adela Deng

### PR DESCRIPTION
**Pull request by dengyijia**

### CODE REVIEW

**Comment by borjasotomayor** [comment]
Please make sure you add a reviewer other than your senior developer, and to set the Projects and Milestone fields appropriately (see the end of https://uchicago-cs.github.io/cmsc22000/labs/advanced-git/ for more details)

**Comment by dengyijia** [comment]
How should I edit my pull or make a new request to include the reviewers?

**Comment by borjasotomayor** [comment]
You should be able to edit this pull request.

**Comment by borjasotomayor** [comment]
You have to request review from an individual developer in your team, not from the entire team (cmsc22000-project-2018/team-tries). I have manually removed that reviewer.

**Comment by mpcsh** [comment]
@dengyijia: please don't tag your whole team for review. You should request review from **one** teammate, as well as your senior developer (myself). I've removed the other teammates, please choose one (arbitrarily) to request review from and add them and myself.

**Pull request merged**
